### ISSUE TITLE
Import error, cannot load Qt4Agg backend

### ISSUE THREAD

**Issue by HRSAstro** [pjcigan/multicolorfits#2]
I get the error
ImportError: Cannot load backend 'Qt4Agg' which requires the 'qt4' interactive framework, as 'qt5' is currently running
when importing the package.

I'm using Python 3.7. According to the README, both qt4 and qt5 should work. I tried installing in a new anaconda environment, but the same problem.

Is there a solution?

**Comment by pjcigan** [comment]
Hello, and thanks for reaching out.  I also noticed this a couple days ago when trying to install on a fresh system.  It appears that one of the traitsui imports changed.  Bug is now fixed in v2.0.3 which is live now in the master github repo, and it should trickle over to pip soon. 
Cheers
