### ISSUE TITLE
Is there a simple way to save the .png of a three colour image created in a script? 

### ISSUE THREAD

**Issue by ashleythomasbarnes** [pjcigan/multicolorfits#3]
I'm using `version = '2.0.2'`, and am getting some errors when trying to save the three colour images I made in a script. I found the following workaround for this, but was wondering if there is an implementation of this I missed? 

```
 all_colRGB = mcf.combine_multicolor([colorRGB1,colorRGB2,colorRGB3])
 all_colRBG_s = (all_colRGB*255).astype(np.uint8)
 alpha = Image.fromarray(all_colRBG_s[::-1], mode="RGB")
 alpha.save('rgb.png', format='png')
```

**Comment by pjcigan** [comment]
Hello,
Is this from the quickview save function,  mcf.plotsinglemulticolorRGB , or another method of saving an image?
What kind of errors do you get?  Would you mind sharing the output when it crashes to help the diagnosis?  

Once the combined multicolor image is created (with mcf.combine_multicolor) it's essentially just a numpy array, so you should be able to plot it directly with your favorite tool for displaying images.  matplotlib/pyplot imshow or pcolormesh, astropy, kapteyn, Image, etc.  The convenience function mcf.plotsinglemulticolorRGB is really just using pyplot.imshow to plot the combined image, and making some simple adjustments of axis labels etc. before using pyplot.savefig to save the image.  So there may be a hiccup in the middle part somewhere, adjusting the axes.  Once I see the exact errors I can get a better idea.  Thanks!
Cheers
P.S. Now that I look at the example pages again, I see that I never mentioned any examples of how to save a figure manually (like your workaround).  I'll try to add something in the next update.



    On Monday, February 28, 2022, 10:54:35 AM EST, Ashley Barnes ***@***.***> wrote:  
 
 


I'm using version = '2.0.2', and am getting some errors when trying to save the three colour images I made in a script. I found the following workaround for this, but was wondering if there is an implementation of this I missed?
 all_colRGB = mcf.combine_multicolor([colorRGB1,colorRGB2,colorRGB3])
 all_colRBG_s = (all_colRGB*255).astype(np.uint8)
 alpha = Image.fromarray(all_colRBG_s[::-1], mode="RGB")
 alpha.save('rgb.png', format='png')

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
